      #此处common模块在上线之后不提供启动类。   值打包成jar供其他模块调用。 这里配置端口值为了common模块的人员测试用
spring:
  jmx:
    enabled: false
  # 环境 dev|test|pro|branch
  profiles:
    active: pro
    include: js
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  datasource:
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 100
      max-wait: 20000
#      default-auto-commit: true
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 3096699800@qq.com #发送邮件的邮箱地址
    password: oppydvptxgrzdeih   #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 3096699800@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
server:
  port: 8080

yaodou:
  dispatcher: http://localhost:9999

mybatis:
  type-aliases-package: com.alibaba.mapper
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
     com.alibaba: debug
